spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
