spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true

mybatis:
  config-location: classpath:db/mybatis/config.xml


wxpay:
  appId: xxxxx
  mchId: xxxxx
  mchKey: xxxxx
  notifyUrl: http://xxx/pay/notify
  returnUrl: http://xxx

alipay:
  appId: xxxxxx
  privateKey: xxxxxx
  publicKey: xxxxxx
  notifyUrl: http://xxx/pay/notify
  returnUrl: http://xxx



